name: Docker Image CI

on: workflow_dispatch

jobs:
  docker-build:
    permissions:
      contents: read
  
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-sample-image
